# Basic Information
email: stanley.lo.2754@gmail.com  # Your Gmail address that you enabled API access for
full_name: Stanley Lo    # Your full name as you want it to appear in emails
name: Stanley        # Your first name for casual communications

# Personal Background
background: |
  I am a student at Claremont McKenna College studying Economics and Data Science. I am passionate about leveraging AI to build helpful applications.

# Schedule & Meeting Preferences
schedule_preferences: |
  - Default meeting length is 30 minutes.
  - Please leave a 15-minute buffer between meetings.
  - I do not take meetings on Saturday or Sunday.
  - Preferred meeting times are generally 9 AM - 5 PM on weekdays.

# Communication Preferences
background_preferences: |
  - For now, I am the only one who needs to be on emails.

response_preferences: |
  - When scheduling, please be proactive and suggest a few specific times.
  - Always confirm receipt of important documents or requests.

# Location
timezone: "PST"  # Your timezone (e.g., "PST", "EST", "UTC")

# Writing Style
rewrite_preferences: |
  My writing style is generally semi-formal but casual. It should always sound human, not like a bot.
  Key principles:
  - Be clear, concise, and friendly.
  - Use a positive and proactive tone.
  - For initial outreach, be polite and state the purpose of the email clearly.
  - For follow-ups, gently remind the recipient of the previous message and suggest a next step.
  - For calendar confirmations, make sure the time, date, and attendees are clearly listed.
  - For post-meeting thank yous, briefly summarize the key takeaways and express gratitude for their time.

# Email Filtering Preferences
triage_no: |
  - Obvious spam or marketing newsletters that I did not subscribe to.
  - Social media notifications (LinkedIn, etc.).
  - Automated system notifications unless they indicate a critical failure.

triage_notify: |
  - Non-urgent project updates or document-sharing notifications (e.g., Google Docs).
  - Meeting cancellations or reschedules.
  - General industry news or updates.

triage_email: |
  - Direct questions from anyone.
  - Meeting scheduling requests.
  - Client or collaborator inquiries.
  - Time-sensitive requests.
  - Any email where I am the primary recipient and a response is clearly expected.

# Enable Memory
memory: true  # Keep this true to allow the assistant to learn from interactions
